# Data Science Excercise 1

#  let I and P represent the ingredients  and  price of ingredients respectively 

# Assumming that the prices of all ingredients were fluctuating for all the days hence a (5*5) five by five matrix as seen below

In [55]:
import numpy as np

 
#indices for the ingredients, let T,O,G,C and P represent Tomatoes,Onions,Garlic, Carrots and Paper respectively


I = np.matrix('[ 2,9,3,10,4;3,2,5,2,6; 4,1,3,7,3; 5,8,10,5,2;  6,2,4,1,1]')
  
P = np.matrix('[300,400,600,700,800;100,200,300,600,500;120,100,200,400,300;200,300,400,500,400;250,350,450,550,200]')
 
#Days
print('Monday:',I[0][0])
print('Tuesday:',I[1][0])
print('Wednesday:',I[2][0]) 
print('Thursday:',I[3][0]) 
print('Friday:',I[4][0]) 
print('\n')


#number of dimensions
print('I and P are a two dimensional matrices:',I.ndim, P.ndim)
print('\n')


# Multiplication of the matrices I and P
print('Product of Ingredients and their price is:\n',I.dot(P))





Monday: [[ 2  9  3 10  4]]
Tuesday: [[3 2 5 2 6]]
Wednesday: [[4 1 3 7 3]]
Thursday: [[ 5  8 10  5  2]]
Friday: [[6 2 4 1 1]]


I and P are a two dimensional matrices: 2 2


Determinant of I is: -9683.999999999998


Product of Ingredients and their price is:
 [[ 4860  7300 10300 15200 11800]
 [ 3600  4800  6900  9600  6900]
 [ 3810  5250  7450  9750  8000]
 [ 5000  6800 10300 15900 13400]
 [ 2930  3850  5850  8050  7600]]


In [56]:
#Transpose of I
print(I.transpose())

[[ 2  3  4  5  6]
 [ 9  2  1  8  2]
 [ 3  5  3 10  4]
 [10  2  7  5  1]
 [ 4  6  3  2  1]]


In [57]:
#Transpose of P
print(P.transpose())

[[300 100 120 200 250]
 [400 200 100 300 350]
 [600 300 200 400 450]
 [700 600 400 500 550]
 [800 500 300 400 200]]


In [30]:
#Determinant of I
det = np.linalg.det(I)
print('Determinant of I is:',det)
print('\n')

-9683.999999999998


In [32]:
#Determinant of P
det_P  = np.linalg.det(P)
print(det_P)

-39000000000.0


In [33]:
#Inverse of I
invI = np.linalg.inv(I)
print(invI)

[[ 0.03541925 -0.0291202  -0.01084263 -0.09520859  0.25598926]
 [ 0.12938868 -0.00433705 -0.18246592 -0.0212722   0.09840975]
 [-0.1287691   0.01548947  0.08023544  0.17121024 -0.1609872 ]
 [-0.00402726 -0.07249071  0.16449814  0.02540273 -0.09324659]
 [ 0.04781082  0.19392813 -0.05545229 -0.09644775  0.00444031]]


In [34]:
#Inverse of P
invP = np.linalg.inv(P)
print(invP)

[[-0.01923077 -0.02179487  0.02435897  0.05897436 -0.02307692]
 [-0.02769231 -0.01205128  0.00641026  0.08025641 -0.02923077]
 [ 0.03923077  0.02179487 -0.02435897 -0.10897436  0.04307692]
 [-0.00461538  0.00076923  0.00384615  0.00615385 -0.00153846]
 [-0.00307692 -0.00282051  0.0025641   0.01410256 -0.00769231]]


In [59]:
#identity matrix
# let id represent the identity matrix of a five by five
id = np.identity(5)
print('\n',id)
print('\n')

#Finding the identity product of I
print('Identity matrix of I is\n:', I.dot(id))



 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Identity matrix of I is
: [[ 2.  9.  3. 10.  4.]
 [ 3.  2.  5.  2.  6.]
 [ 4.  1.  3.  7.  3.]
 [ 5.  8. 10.  5.  2.]
 [ 6.  2.  4.  1.  1.]]


In [ ]:
#The matrices are linearly dependant with the fact that their determinants are not zero 

# End of Excercise

# Using a Column Matrix


In [37]:
import numpy as np

I = np.matrix('[ 2,9,3,10,4;3,2,5,2,6; 4,1,3,7,3; 5,8,10,5,2;  6,2,4,1,1]')
P = np.matrix('[300;400;500;600;700]')

#product
product = I.dot(P)
print('Product of I and P is: \n',product)

Product of I and P is: 
 [[14500]
 [ 9600]
 [ 9400]
 [14100]
 [ 5900]]


In [53]:
#transpose I
print(I.transpose())

[[ 2  3  4  5  6]
 [ 9  2  1  8  2]
 [ 3  5  3 10  4]
 [10  2  7  5  1]
 [ 4  6  3  2  1]]


In [34]:
#transpose P
print('P transpose is:',P.transpose())

P transpose is: [[300 100 120 200 250]
 [400 200 100 300 350]
 [600 300 200 400 450]
 [700 600 400 500 550]
 [800 500 300 400 200]]


In [31]:
#Determinant of I
det = np.linalg.det(I)
print('Determinant of I is :',round(det))

Determinant of I is : -9684


#Determinant of a coloumn vector or matrix cannot be done hence P is linearly independant


In [70]:
#inverse of I
invI = np.linalg.inv(I)
print(invI )

[[ 0.03541925 -0.0291202  -0.01084263 -0.09520859  0.25598926]
 [ 0.12938868 -0.00433705 -0.18246592 -0.0212722   0.09840975]
 [-0.1287691   0.01548947  0.08023544  0.17121024 -0.1609872 ]
 [-0.00402726 -0.07249071  0.16449814  0.02540273 -0.09324659]
 [ 0.04781082  0.19392813 -0.05545229 -0.09644775  0.00444031]]


In [ ]:
#inverse of P 
#This cannot be found with the fact that P is a column vector/matrix hence no major diagonal hence the determinant cannot be found